name: build
# Events configuration
on:
  # Execute it on pushing to next branches
  push:
    branches: 
      - main
      - release
  # Execute it on opening any pull request
  pull_request:
jobs:
  branch-info:
    runs-on: ubuntu-latest
    steps:
      - name: Get branch name
        id: get-branch-name
        run: |
            if [[ "${{github.event.pull_request.base.ref}}" != "" ]]; then
              echo "${{github.event.pull_request.base.ref}}"
              echo "::set-output name=branch::${{github.event.pull_request.base.ref}}"
            else
              echo "${{github.ref_name}}"
              echo "::set-output name=branch::${{github.ref_name}}"
            fi
    outputs:
      branch-name: ${{ steps.get-branch-name.outputs.branch }}
  # Our first job
  get-affected:
    needs: [branch-info]
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # Configure Nx to be able to detect changes between branches when we are in a PR
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
        with:
          main-branch-name: ${{needs.branch-info.outputs.branch-name}}
      # Install Pnpm
      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.1
        with:
          version: "6.x"
      # Install Node.js
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: 'pnpm'
      # Install workspace dependencies
      - name: Install dependencies
        run: pnpm install
      - name: Get affected
        id: get-projects-arrays
        run: |
            node scripts/print-affected-array.js test:unit origin/${{needs.branch-info.outputs.branch-name}}
            echo "::set-output name=test-unit::$(node scripts/print-affected-array.js test:unit origin/${{needs.branch-info.outputs.branch-name}})"
            echo "::set-output name=test-e2e::$(node scripts/print-affected-array.js test:e2e origin/${{needs.branch-info.outputs.branch-name}})"
