name: build
# Events configuration
on:
  # Execute it on pushing to next branches
  push:
    branches: 
      - main
      - release
      - test-docs
  # Execute it on opening any pull request
  pull_request:
